// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkJcMtDlTHkUfWyBlq9gan9S-eU5UMsM',
    appId: '1:1027895217608:web:ec646dd21945a5e92504fd',
    messagingSenderId: '1027895217608',
    projectId: 'palangs',
    authDomain: 'palangs.firebaseapp.com',
    storageBucket: 'palangs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxMaa39O755VRfRqNXzIToiTZEQ-uiWw',
    appId: '1:1027895217608:android:e2dad1343eaf91462504fd',
    messagingSenderId: '1027895217608',
    projectId: 'palangs',
    storageBucket: 'palangs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ud6yiM-poNVnit1OjDkTPAAwlQvluJc',
    appId: '1:1027895217608:ios:f1aa586e692f39f12504fd',
    messagingSenderId: '1027895217608',
    projectId: 'palangs',
    storageBucket: 'palangs.appspot.com',
    iosBundleId: 'com.example.palangs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ud6yiM-poNVnit1OjDkTPAAwlQvluJc',
    appId: '1:1027895217608:ios:5e02ad760bb476cf2504fd',
    messagingSenderId: '1027895217608',
    projectId: 'palangs',
    storageBucket: 'palangs.appspot.com',
    iosBundleId: 'com.example.palangs.RunnerTests',
  );
}
